//------------------------------------------------------------------------------
// <auto-generated>
//     Bu kod ara� taraf�ndan olu�turuldu.
//     �al��ma Zaman� S�r�m�:4.0.30319.42000
//
//     Bu dosyada yap�lacak de�i�iklikler yanl�� davran��a neden olabilir ve
//     kod yeniden olu�turulursa kaybolur.
// </auto-generated>
//------------------------------------------------------------------------------

// Source Executable: c:\windows\system32\psmsrv.dll
// Interface ID: bdaa0970-413b-4a3e-9e5d-f6dc9d7e0760
// Interface Version: 1.0
// Client Generated: 8.08.2025 03:36:59
// NtCoreLib Version: 2.0.0+a18af727ad9dc5ac0ff0bbe4a9f03e744f69ae85

namespace rpc_bdaa0970_413b_4a3e_9e5d_f6dc9d7e0760_1_0
{

    #region Marshal Helpers
    internal sealed class _Marshal_Helper : NtCoreLib.Ndr.Marshal.NdrMarshalBufferDelegator
    {
        public _Marshal_Helper() :
                this(new NtCoreLib.Ndr.Marshal.NdrMarshalBuffer())
        {
        }
        public _Marshal_Helper(NtCoreLib.Ndr.Marshal.INdrMarshalBuffer m) :
                base(m)
        {
        }
    }
    internal sealed class _Unmarshal_Helper : NtCoreLib.Ndr.Marshal.NdrUnmarshalBufferDelegator
    {
        public _Unmarshal_Helper(NtCoreLib.Ndr.Marshal.INdrUnmarshalBuffer u) :
                base(u)
        {
        }
    }
    #endregion
    #region Client Implementation
    public sealed class Client : NtCoreLib.Win32.Rpc.Client.RpcClientBase
    {
        public Client() :
                base("bdaa0970-413b-4a3e-9e5d-f6dc9d7e0760", 1, 0)
        {
        }
        private _Unmarshal_Helper SendReceive(int p, _Marshal_Helper @__m)
        {
            return new _Unmarshal_Helper(SendReceiveTransport(p, @__m));
        }
        public int Proc0(out NtCoreLib.Ndr.Marshal.NdrContextHandle p0)
        {
            _Marshal_Helper @__m = new _Marshal_Helper(CreateMarshalBuffer());
            _Unmarshal_Helper @__u = SendReceive(0, @__m);
            try
            {
                p0 = @__u.ReadContextHandle();
                return @__u.ReadInt32();
            }
            finally
            {
                @__u.Dispose();
            }
        }
        public int Ordinal2(NtCoreLib.Ndr.Marshal.NdrContextHandle p0, NtCoreLib.Ndr.Marshal.NdrUInt3264 p1, int p2, sbyte p3)
        {
            _Marshal_Helper @__m = new _Marshal_Helper(CreateMarshalBuffer());
            @__m.WriteContextHandle(p0);
            @__m.WriteUInt3264(p1);
            @__m.WriteInt32(p2);
            @__m.WriteSByte(p3);
            _Unmarshal_Helper @__u = SendReceive(1, @__m);
            try
            {
                return @__u.ReadInt32();
            }
            finally
            {
                @__u.Dispose();
            }
        }
        public int Ordinal3(NtCoreLib.Ndr.Marshal.NdrContextHandle p0, NtCoreLib.Ndr.Marshal.NdrUInt3264 p1, int p2)
        {
            _Marshal_Helper @__m = new _Marshal_Helper(CreateMarshalBuffer());
            @__m.WriteContextHandle(p0);
            @__m.WriteUInt3264(p1);
            @__m.WriteInt32(p2);
            _Unmarshal_Helper @__u = SendReceive(2, @__m);
            try
            {
                return @__u.ReadInt32();
            }
            finally
            {
                @__u.Dispose();
            }
        }
        public int Ordinal3_3(ref NtCoreLib.Ndr.Marshal.NdrContextHandle p0)
        {
            _Marshal_Helper @__m = new _Marshal_Helper(CreateMarshalBuffer());
            @__m.WriteContextHandle(p0);
            _Unmarshal_Helper @__u = SendReceive(3, @__m);
            try
            {
                p0 = @__u.ReadContextHandle();
                return @__u.ReadInt32();
            }
            finally
            {
                @__u.Dispose();
            }
        }
        public int Ordinal2_4(NtCoreLib.Ndr.Marshal.NdrContextHandle p0, NtCoreLib.Ndr.Marshal.NdrUInt3264 p1, out int p2)
        {
            _Marshal_Helper @__m = new _Marshal_Helper(CreateMarshalBuffer());
            @__m.WriteContextHandle(p0);
            @__m.WriteUInt3264(p1);
            _Unmarshal_Helper @__u = SendReceive(4, @__m);
            try
            {
                p2 = @__u.ReadInt32();
                return @__u.ReadInt32();
            }
            finally
            {
                @__u.Dispose();
            }
        }
    }
    #endregion
}

